name: Build and Publish

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install Dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js for NPM Publishing
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure .npmrc
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.GTH_TOKEN }}" > ~/.npmrc
      
      # Optionally run `npm ci` to ensure clean install before publishing
      # - name: Clean Install Dependencies
      #   run: npm ci

      - name: Publish to NPM
        run: npm publish
        env:
          GTH_TOKEN: ${{ secrets.GTH_TOKEN }}
